In [20]:
import numpy as np
import pandas as pd


In [21]:
import warnings
warnings.filterwarnings('ignore')

In [22]:
import tensorflow as tf


In [23]:
print(tf.__version__)

2.1.0


In [24]:
# import logging
# logger = tf.get_logger()
# logger.setLevel(logging.ERROR)

### Create a tensor with random values with 5 inputs


In [25]:
# Set the random seed so that things are reproducible
tf.random.set_seed(7)

# Create 5 random input features
features = tf.random.normal((1,5))

# Create random weights for your neural network
weights = tf.random.normal((1,5))

# Create random bias term for our neural network
bias = tf.random.normal((1,1))

print('Features:\n',features)
print('Weights:\n',weights)
print('Bias:\n',bias)

Features:
 tf.Tensor([[ 0.5983449   0.06276207  0.14631742  0.48481876 -0.23572342]], shape=(1, 5), dtype=float32)
Weights:
 tf.Tensor([[-2.2733312  -1.6592104  -0.2633568  -0.80923414  1.0294315 ]], shape=(1, 5), dtype=float32)
Bias:
 tf.Tensor([[1.5749502]], shape=(1, 1), dtype=float32)


In [26]:
# Define activation function
def sigmoid_activation(x):
    return 1/(1 + tf.exp(-x))

In [28]:
# To create output of the function
y = sigmoid_activation(tf.reduce_sum(tf.multiply(features, weights)) + bias)
print('Label:\n',y)

Label:
 tf.Tensor([[0.3628656]], shape=(1, 1), dtype=float32)


tf.Tensor(0.9967855, shape=(), dtype=float32)
